AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  GithubOIDCRole:
    Type: String
    Description: "Github OIDC Role that will assume the deployment role created here."
Resources:
  CDKDeployRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName:
        !Sub "TerraformDeploymentRole-${AWS::Region}-${AWS::AccountId}"
      Description: "Role to deploy CDK resources."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Federated:
                  - 'arn:aws:iam::362055466028:oidc-provider/token.actions.githubusercontent.com'
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - "repo:cullancarey/website:*"
              StringEquals:
                token.actions.githubusercontent.com:aud:
                  - 'sts.amazonaws.com'
      Path: /
      Policies:
        - PolicyName: "TerraformRoleDeployPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: "*"